language: node_js
sudo: false
dist: trusty
node_js: '9'
addons:
  chrome: stable
cache:
  directories:
  - node_modules
script:
- xvfb-run npm run test -- -l chrome
- wct -s 'windows 10/microsoftedge@15'
env:
  global:
  - secure: k3PUHHiSoOdy6NapWE7dpuO5y0rNqLHpNL+72MTjK72YuvPe7mpB1ihrEv51MRJJTQqU1KD9E/aiIH7eG4BxoPkYM2mavi4mkyK/fwKCaKzq/9a7HTDeF8cvSO8ekpXx17RzxHEgrRoRzOnh2dbONco3evgUh7ShiwsV3EaDW72iVxYCswgoD4R4CaPQcP6ASOj+SKHYYUE9xque0I6wcI8fkvWJ4HdbNr3Mm1P+fxLpqZJQ7OjPhtXrInOfUo9LzpOzMNqNi5rGADOOhehUrFWK+F/shHJeI/AwAbEfT+dTfIF9j0jSj7ZXH4heoCCA4zFMxYLbdKtChaeidrAyOIczw+gLYa4mqXF+TOhFL3W0ywUQpzt7Rb1BsT566oHyEi14Z1MxJ8lCZsCajyERhDkGgSLlQwDG95U78voP6wDPRrQFUrsksMYD0bxqc1e4k33f30cjLcxkr25tSZQp/5W5e9c3+83IAd3JAppT9DT0BTf8o/gqoArrn9FsiV3RjWGR3t5Nyn/SMBSw3GjlFGgcvOryN9EKOEGdsPDHzE56zipQmCIMMFrlkNC6n8mJTrWbnY4KR/XdepECCJV3/oQZfZL9BSD+YnY+3hi6oPfla7UnUMPqKF6zNTQ8qSuvA7PUtZ2WYUaRvHdA1qZp22p5FUfI7+P/xu1slrWi7A0=
  - secure: TOlPAqB40NXcBS9MuJfTdmUBy+uhRfv2nZc2cST7I7v7xJhhGPvkGJYnyhpEMFkX2s65IlqnaazptBLghYdIXfC744zAG7BNhCzNL9BCTzlob1orhXNE1y5yuRZ69mMjCerzAghMOOX32bf+0hS5JK6HGa4ks1pKyr69qFHcuTVnLmGpenYcOOlNr7XDghOniF4/BVF5Zn3zr240fpDw8uYvGBRVcDhdRU/uuJVRgrjg+xQS/WlwzYk2qM+miQ9Tc9FNdm2/QbWAGQ9uGEQIudd8e3TAGJiHvdLsvMdVoI1hLnzIT/0PVf2Raq69nbKrVlfhnl4u5bnAhzPYPs/UL+W1PzbMd71Wc8m2grF7D6RNg4tatOWazkaBJ0Gog8tCpJ1IB8rhAqBZOXtjx41Avuam9jwjZ8RAjTlkGewCc8ZwRHrjGsCpkyqZeDRf2avMf9936If/80+EETdHmnx5qiOfbiUwWjA8Xo9JFCfG4Pmf48vt+jzX2JJGVg7k+8AjY4YqzJT179SUvlA1PkudNIcltbsmu8cgr9VwMLf3RTgX32oLkxCNaKRs88ohlpP8vdBZWZzd2WUZrcff989X67kBU8h5da4+gIT3rXMJ93tX1zBr5XRiGevGc8w6EFvK3i3qEpGRjUv/pTxzzULLjjebetdZRGMPNNpR4yh8fRU=
